// Tasuku OpenCode Plugin
// Auto-generated by tk hooks install --opencode
// Provides Tasuku integration hooks for OpenCode sessions

export const TasukuPlugin = async ({ project, client, $, directory }) => {
  // Helper to run tk commands
  const tk = async (...args) => {
    try {
      const result = await $`tk ${args.join(' ')}`;
      return result.text();
    } catch (e) {
      return '';
    }
  };

  // Helper to send notifications (nudges)
  const notify = (msg) => {
    // CRITICAL: Always log to the session so the AGENT sees the nudge (Autonomy)
    client.app.log('info', msg);

    // Also notify the HUMAN (Visibility)
    if (client.app.notify) {
      client.app.notify(msg);
    } else if (client.app.toast) {
      client.app.toast(msg);
    }
  };

  return {
    // Show context summary when session starts
    'session.created': async (event) => {
      const output = await tk('hooks', 'session');
      if (output.trim()) {
        client.app.log('info', output);
      }
    },

    // Remind about running timers when session goes idle
    'session.idle': async (event) => {
      const output = await tk('hooks', 'stop-reminder');
      if (output.trim()) {
        client.app.log('info', output);
      }
    },

    // Check TodoWrite output for project-level tasks and completed bug fixes
    'todo.updated': async (event) => {
      if (!event.todos || event.todos.length === 0) return;

      // Run todo check for:
      // 1. Completed bug fixes (to prompt for learnings)
      // 2. Project-level tasks that should be persisted
      const hasRelevantItems = event.todos.some(t =>
        t.status === 'completed' || t.status === 'pending' || t.status === 'in_progress'
      );
      if (!hasRelevantItems) return;

      // Run todo check (it reads from environment)
      process.env.TOOL_INPUT = JSON.stringify({ todos: event.todos });
      const output = await tk('hooks', 'todo-check');
      if (output.trim()) {
        notify(output);
      }
    },

    // Check tool execution for Bash (tests/git) and Task (subagents)
    'tool.execute.after': async (event) => {
      const tool = event.tool?.toLowerCase();
      if (!tool) return;

      // Handle Bash checks (tests, git)
      if (tool === 'bash') {
        process.env.TOOL_NAME = 'Bash';
        process.env.TOOL_INPUT = JSON.stringify(event.input || {});
        process.env.TOOL_OUTPUT = event.output || '';
        const output = await tk('hooks', 'todo-check');
        if (output.trim()) notify(output);
        return;
      }

      // Handle Subagent completion (pipe JSON on stdin like other hooks)
      if (tool === 'task') {
        const hookCmd = 'subagent-done';
        const stdinData = JSON.stringify({ subagent_type: event.input?.subagent_type || 'general' });
        try {
          const result = await $`echo ${stdinData} | tk hooks ${hookCmd}`;
          const output = result.text();
          if (output.trim()) notify(output);
        } catch (e) {}
        return;
      }
    },

    // Check user prompts for context surfacing and nudges
    'message.created': async (event) => {
      if (event.role === 'user') {
        process.env.USER_PROMPT = event.content;
        const output = await tk('hooks', 'prompt-check');
        if (output.trim()) notify(output);
      }
    },
  };
};

// Export as default for OpenCode plugin discovery
export default TasukuPlugin;
